name: Qualidade Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-tests:
    name: Testes e Cobertura (JUnit + JaCoCo)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/gerenciadorescolar

    steps:
      - name: Checkout do c贸digo
        uses: actions/checkout@v3

      - name: Instalar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar testes com cobertura
        run: mvn clean test

      - name: Gerar relat贸rio JaCoCo
        run: mvn jacoco:report

      - name: Upload do relat贸rio de cobertura
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-cobertura
          path: target/site/jacoco

      - name: Baixar OWASP Dependency Check CLI
        run: |
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v8.3.2/dependency-check-8.3.2-release.zip
          unzip dependency-check-8.3.2-release.zip

      - name: Rodar OWASP Dependency Check
        run: |
          ./dependency-check/bin/dependency-check.sh --project "GerenciadorEscolar" --scan ./backend/gerenciadorescolar --format "HTML" --out ./dependency-check-report

      - name: Upload do relat贸rio OWASP
        uses: actions/upload-artifact@v4
        with:
          name: owasp-report
          path: ./dependency-check-report