name: Qualidade

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-tests:
    name: Testes, Cobertura e OWASP
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/gerenciadorescolar

    steps:
      - name: Checkout do c贸digo
        uses: actions/checkout@v3

      - name: Instalar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar testes com cobertura
        run: mvn clean test

      - name: Gerar relat贸rio JaCoCo
        run: mvn jacoco:report

      - name: Upload do relat贸rio de cobertura
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-cobertura
          path: target/site/jacoco

      - name: Baixar OWASP Dependency Check
        run: |
          curl -L -o dc.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.2.1/dependency-check-8.2.1-release.zip
          unzip dc.zip -d dc

      - name: Executar OWASP Dependency Check (formato seguro)
        run: |
          ./dc/dependency-check/bin/dependency-check.sh \
            --project "gerenciadorescolar" \
            --scan ./ \
            --format XML \
            --out ./owasp-report \
            --failOnCVSS 7 \
            --disableAssembly

      - name: Upload do relat贸rio OWASP
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-owasp
          path: backend/gerenciadorescolar/owasp-report
